### ISSUE TITLE
Programmatically download from TIMEDB website

### ISSUE THREAD

**Issue by aoumess** [deepomicslab/TIMEDB#3]
Hi,

Is there a way to programmatically download some data tables from TIMEDB website ?
By example, I want to get any "LUAD-like" dataset, which currently are 23 different datasets. Manually downloading multiple data types for each is a real pain, thus I wanted to script this step. Unfortunately, I have not been able to perform it, be it with curl or wget, messing with redirection options, custom user agent, etc... : I always end up with a dump of a redirection file, or the HTML version of the main site page... 
Do you have any idea ?
Thanks !

**Comment by kristaxying** [comment]
Hi~
I'm sorry to inform you that programmatically downloading data from the TIMEDB website is not allowed due to it being hosted on a university server. Such actions may violate the terms of use and policies of the university's server.

However, I have good news for you. The TIMEDB website has a download page that provides access to pre-organized datasets. You can find the download page by clicking on the "Download" button on the top menu of the TIMEDB website. On the download page, you can select the dataset(s) you are interested in and download them in various formats.

I hope this information helps, and please let me know if you have any further questions or concerns.
