### ISSUE TITLE
Unable to Access TIMEDB Database from Published Article

### ISSUE THREAD

**Issue by KarthikDani** [deepomicslab/TIMEDB#5]
Hi,

I recently encountered an issue with a broken link in the published article titled ["TIMEDB: tumor immune micro-environment cell composition database with automatic analysis and interactive visualization"](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9825442/). The article references a link to the TIMEDB database, specifically [https://timedb.deepomics.org/](https://timedb.deepomics.org/), which appears to be broken.

This prevents us from accessing important supplementary data and resources mentioned in the article.

Please let me know if there are alternative ways to access the TIMEDB database or if there is an updated link available. Thank you for your assistance.

Best regards,
Karthik.

**Comment by kristaxying** [comment]
Hi Karthik,

Thank you for bringing this issue to my attention. I apologize for the inconvenience caused by the broken link to the TIMEDB database.

The TIMEDB website (https://timedb.deepomics.org/) is temporarily offline due to server maintenance, and is expected to be back online and fully operational by tomorrow.


Best regards,
Xueying

**Comment by kristaxying** [comment]
Hi Karthik,

Thank you for bringing this issue to my attention. I apologize for the inconvenience caused by the broken link to the TIMEDB database.

The TIMEDB website (https://timedb.deepomics.org/) is temporarily offline due to server maintenance, and is expected to be back online and fully operational by tomorrow.

Best regards,
Xueying

**Comment by kristaxying** [comment]
Hi Karthik,

The website is now back online.

Best regards,
Xueying

**Comment by kristaxying** [comment]
Hi Karthik,

The website is now back online.

Best regards,
Xueying

**Comment by KarthikDani** [comment]
Thank you! 

Regards,
Karthik.
